### ISSUE TITLE
No matching distribution found for DCNv4==latest

### ISSUE THREAD

**Issue by chihchiehchen** [OpenGVLab/DCNv4#1]
Hello,

Thanks for releasing the open source code. I tried to follow the instruction (DCNv4/segmentation/readme.md) to install DCNv4, but encountering an error message that says "RROR: Could not find a version that satisfies the requirement DCNv4==latest ERROR: No matching distribution found for DCNv4==latest". When I typed "pip install DCNv4", I encountered the following error message: 

>site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
      return torch._C._cuda_getDeviceCount() > 0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kox_k2e6/dcnv4_191e7104a4a646c5a96941957ab1b8ee/setup.py", line 70, in <module>
        ext_modules=get_extensions(),
      File "/tmp/pip-install-kox_k2e6/dcnv4_191e7104a4a646c5a96941957ab1b8ee/setup.py", line 48, in get_extensions
        raise NotImplementedError('Cuda is not available')
    NotImplementedError: Cuda is not available
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.2'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Could you give me some hints for this problems? In any case thanks a lot!

**Comment by zhiqi-li** [comment]
sorry for that, you can try `pip install DCNv4`

**Comment by zhiqi-li** [comment]
Do you have cuda in your env?

**Comment by chihchiehchen** [comment]
Oh, sorry I forgot to install cuda and cudnn. Let me see if I can install that successfully. 

In any case, thanks a lot!
