### ISSUE TITLE
Error model param shape: cascade_flash_internimage_l_fpn_3x_coco.pth

### ISSUE THREAD

**Issue by billbliss3** [OpenGVLab/DCNv4#10]
It seems that: some params' shape is not matched.

RuntimeError: Error(s) in loading state_dict for FlashInternImage:
        size mismatch for levels.0.blocks.0.dcn.offset_mask.weight: copying a param with shape torch.Size([270, 160]) from checkpoint, the shape in current model is torch.Size([272, 160]).
        size mismatch for levels.0.blocks.0.dcn.offset_mask.bias: copying a param with shape torch.Size([270]) from checkpoint, the shape in current model is torch.Size([272]).
        size mismatch for levels.0.blocks.1.dcn.offset_mask.weight: copying a param with shape torch.Size([270, 160]) from checkpoint, the shape in current model is torch.Size([272, 160]).
        size mismatch for levels.0.blocks.1.dcn.offset_mask.bias: copying a param with shape torch.Size([270]) from checkpoint, the shape in current model is torch.Size([272]).
        size mismatch for levels.0.blocks.2.dcn.offset_mask.weight: copying a param with shape torch.Size([270, 160]) from checkpoint, the shape in current model is torch.Size([272, 160]).
        size mismatch for levels.0.blocks.2.dcn.offset_mask.bias: copying a param with shape torch.Size([270]) from checkpoint, the shape in current model is torch.Size([272]).
        size mismatch for levels.0.blocks.3.dcn.offset_mask.weight: copying a param with shape torch.Size([270, 160]) from checkpoint, the shape in current model is torch.Size([272, 160]).
        size mismatch for levels.0.blocks.3.dcn.offset_mask.bias: copying a param with shape torch.Size([270]) from checkpoint, the shape in current model is torch.Size([272]).
        size mismatch for levels.0.blocks.4.dcn.offset_mask.weight: copying a param with shape torch.Size([270, 160]) from checkpoint, the shape in current model is torch.Size([272, 160]).
        size mismatch for levels.0.blocks.4.dcn.offset_mask.bias: copying a param with shape torch.Size([270]) from checkpoint, the shape in current model is torch.Size([272]).
        size mismatch for levels.1.blocks.0.dcn.offset_mask.weight: copying a param with shape torch.Size([540, 320]) from checkpoint, the shape in current model is torch.Size([544, 320]).
        size mismatch for levels.1.blocks.0.dcn.offset_mask.bias: copying a param with shape torch.Size([540]) from checkpoint, the shape in current model is torch.Size([544]).
        size mismatch for levels.1.blocks.1.dcn.offset_mask.weight: copying a param with shape torch.Size([540, 320]) from checkpoint, the shape in current model is torch.Size([544, 320]).
        size mismatch for levels.1.blocks.1.dcn.offset_mask.bias: copying a param with shape torch.Size([540]) from checkpoint, the shape in current model is torch.Size([544]).
        size mismatch for levels.1.blocks.2.dcn.offset_mask.weight: copying a param with shape torch.Size([540, 320]) from checkpoint, the shape in current model is torch.Size([544, 320]).
        size mismatch for levels.1.blocks.2.dcn.offset_mask.bias: copying a param with shape torch.Size([540]) from checkpoint, the shape in current model is torch.Size([544]).
        size mismatch for levels.1.blocks.3.dcn.offset_mask.weight: copying a param with shape torch.Size([540, 320]) from checkpoint, the shape in current model is torch.Size([544, 320]).
        size mismatch for levels.1.blocks.3.dcn.offset_mask.bias: copying a param with shape torch.Size([540]) from checkpoint, the shape in current model is torch.Size([544]).
        size mismatch for levels.1.blocks.4.dcn.offset_mask.weight: copying a param with shape torch.Size([540, 320]) from checkpoint, the shape in current model is torch.Size([544, 320]).
        size mismatch for levels.1.blocks.4.dcn.offset_mask.bias: copying a param with shape torch.Size([540]) from checkpoint, the shape in current model is torch.Size([544]).
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 12676) of binary: /opt/conda/bin/python

**Comment by zhiqi-li** [comment]
I used the latest code to re-verify this checkpoint and did not encounter this problem. Please try again using the latest codebase and DCNv4 package. If you still encounter the same problem, please provide us with more detailed information.

**Comment by billbliss3** [comment]
您好，您的来件已收到，我会尽快给您回复的。

Thanks for you e-mail.~~
I've got it and I will reply it as soon as possible .

**Comment by billbliss3** [comment]
@zhiqi-li 
李博您好：

需要复现 参数形状的不同，需要修复一处checkpoint载入的问题。

存在格式的不兼容，下划线分格 vs 点分格。
checkpoint参数的表达: 如 ema_backbone_patch_embed_XXX_offset_mask_dw
而模型参数表达是patch.embed.XXX.offset.mask.dw

如果要载入cascade_flash_internimage_l_fpn_3x_coco.pth参数并复线我遇到的问题。

在flashInternImage中，我将初始化函数
class FlashInternImage(nn.Module): def __init__()中的

            state_dict = OrderedDict()
            for k, v in _state_dict.items():
                if k.startswith('backbone.'):
                    state_dict[k[9:]] = v
                else:
                    state_dict[k] = v

修改成了
            state_dict = OrderedDict()
            backbone_prefix = 'ema_backbone_'
            prefix_len = len(backbone_prefix)
            for k, v in _state_dict.items():
                if k.startswith(backbone_prefix):
                    # replace all '.'
                    k = k[prefix_len:].replace('_', '.')
                    # restore keywords '_'
                    k = k.replace('patch.embed', 'patch_embed')
                    k = k.replace('offset.mask.dw', 'offset_mask_dw')
                    k = k.replace('offset.mask', 'offset_mask')
                    k = k.replace('value.proj', 'value_proj')
                    k = k.replace('output.proj', 'output_proj')
                    state_dict[k] = v

**Comment by zhiqi-li** [comment]
您好，改checkpoint 同时存在ema 和非ema参数，加载该checkpoint不会使用ema参数。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by billbliss3** [comment]
谢谢。确实：同时存在ema 和非ema参数，加载该checkpoint不会使用ema参数。
