### ISSUE TITLE
mask2former_flash_internimage_b_640_160k_ade20k_ss.pth file seems broken.

### ISSUE THREAD

**Issue by billbliss3** [OpenGVLab/DCNv4#11]
mask2former_flash_internimage_b_640_160k_ade20k_ss.pth file seems broken.

**Comment by billbliss3** [comment]
mask2former_flash_internimage_l_640_160k_ade20k_ss.pth is broken too.

RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by zhiqi-li** [comment]
Sorry for that. We re-uploaded the correct checkpoints.
