### ISSUE TITLE
expected scalar type Float but found BFloat16

### ISSUE THREAD

**Issue by jiarenyf** [OpenGVLab/DCNv4#15]
DCNv4/functions/dcnv4_func.py", line 125, in backward
ext.dcnv4_backward(*args)
RuntimeError: expected scalar type Float but found BFloat16

**Comment by jiarenyf** [comment]
=。=真的没人吗，你们训练不用bf16的吗。。。

**Comment by JiaHeng-DLUT** [comment]
+1. same problem.
