### ISSUE TITLE
Can't invoke DCNv4 class after build and install via pip

### ISSUE THREAD

**Issue by 0x6f6f** [OpenGVLab/DCNv4#18]
I have built the DCNv4_op project and installed via `pip install -e .`:

![image](https://github.com/OpenGVLab/DCNv4/assets/129521056/0c583c51-cb98-46c5-93a1-7e8811429072)

but when i'm trying to invoke it into my project, i met such error:

```test
(mmd) zrway@zrpgs:/data/yolov8_proj$ python /data/yolov8_proj/project/test_model.py

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]                
  2                  -1  2    130513  ultralytics.nn.modules.customed.PRC2f.PRC2f  [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]               
  4                  -1  4    888481  ultralytics.nn.modules.customed.PRC2f.PRC2f  [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]              
  6                  -1  4   3546433  ultralytics.nn.modules.customed.PRC2f.PRC2f  [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]              
  8                  -1  2   3512225  ultralytics.nn.modules.customed.PRC2f_DCN_v4.PRC2f_DCN_v4[576, 576, 2, True]           
  9                  -1  1   1670992  ultralytics.nn.modules.customed.SPPF_DCN.SPPF_DCN_v4[576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  2   2660929  ultralytics.nn.modules.customed.PRC2f.PRC2f  [960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  2    703777  ultralytics.nn.modules.customed.PRC2f.PRC2f  [576, 192, 2]                 
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  2   2366017  ultralytics.nn.modules.customed.PRC2f.PRC2f  [576, 384, 2]                 
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  2   5429089  ultralytics.nn.modules.customed.PRC2f.PRC2f  [960, 576, 2]                 
 22        [15, 18, 21]  1   3822016  ultralytics.nn.modules.head.Detect           [80, [192, 384, 576]]         
Traceback (most recent call last):
  File "/data/yolov8_proj/project/test_model.py", line 26, in <module>
    model = YOLO('yolov8m.yaml').load('/data/yolov8_proj/project/yolov8m.pt')
  File "/data/yolov8_proj/ultralytics/ultralytics/engine/model.py", line 92, in __init__
    self._new(model, task)
  File "/data/yolov8_proj/ultralytics/ultralytics/engine/model.py", line 142, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/data/yolov8_proj/ultralytics/ultralytics/nn/tasks.py", line 292, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))])  # forward
  File "/data/yolov8_proj/ultralytics/ultralytics/nn/tasks.py", line 291, in <lambda>
    forward = lambda x: self.forward(x)[0] if isinstance(m, (Segment, Pose, OBB)) else self.forward(x)
  File "/data/yolov8_proj/ultralytics/ultralytics/nn/tasks.py", line 84, in forward
    return self.predict(x, *args, **kwargs)
  File "/data/yolov8_proj/ultralytics/ultralytics/nn/tasks.py", line 102, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "/data/yolov8_proj/ultralytics/ultralytics/nn/tasks.py", line 123, in _predict_once
    x = m(x)  # run
  File "/home/zrway/anaconda3/envs/mmd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/yolov8_proj/ultralytics/ultralytics/nn/modules/customed/PRC2f_DCN_v4.py", line 177, in forward
    y.extend(m(y[-1]) for m in self.m)
  File "/data/yolov8_proj/ultralytics/ultralytics/nn/modules/customed/PRC2f_DCN_v4.py", line 177, in <genexpr>
    y.extend(m(y[-1]) for m in self.m)
  File "/home/zrway/anaconda3/envs/mmd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/yolov8_proj/ultralytics/ultralytics/nn/modules/customed/PRC2f_DCN_v4.py", line 49, in forward
    return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))
  File "/home/zrway/anaconda3/envs/mmd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/yolov8_proj/ultralytics/ultralytics/nn/modules/customed/PRC2f_DCN_v4.py", line 27, in forward
    x = self.dcnv4(
  File "/home/zrway/anaconda3/envs/mmd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/yolov8_proj/deps/DCNv4/DCNv4_op/DCNv4/modules/dcnv4.py", line 130, in forward
    x = DCNv4Function.apply(
  File "/home/zrway/anaconda3/envs/mmd/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 86, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/data/yolov8_proj/deps/DCNv4/DCNv4_op/DCNv4/functions/dcnv4_func.py", line 103, in forward
    output = ext.dcnv4_forward(*args)
RuntimeError: Not implemented on the CPU
```

i'd appreciate it if you chould provide some help to solve this.

**Comment by zhiqi-li** [comment]
We require GPU devices.

**Comment by 0x6f6f** [comment]
gpu is absolutely enabled:

![image](https://github.com/OpenGVLab/DCNv4/assets/129521056/e918788e-3602-4027-90fe-0c3b698558b7)

since in all the revious training process, gpu is sucessfully invoked like this: 

![image](https://github.com/OpenGVLab/DCNv4/assets/129521056/ac656c6f-b8a6-47d1-addf-ce958a847917)

detailed imp of DCNv4 in my code is shown below:

```python
class DCNV4_YOLO(nn.Module):
    def __init__(self, inc, ouc, k=1, s=1, p=None, g=1, d=1, act=True):
        super().__init__()
        
        if inc != ouc:
            self.stem_conv = Conv(inc, ouc, k=1)
        self.dcnv4 = DCNv4(ouc, kernel_size=k, stride=s, pad=autopad(k, p, d), group=g, dilation=d)
        self.bn = nn.BatchNorm2d(ouc)
        self.act = Conv.default_act if act is True else act if isinstance(act, nn.Module) else nn.Identity()
    
    def forward(self, x):
        if hasattr(self, 'stem_conv'):
            x = self.stem_conv(x)
        x = self.dcnv4(
            x.reshape((x.size(0), x.size(1), x.size(2) * x.size(3))).transpose(2, 1), # (N, C, H, W) -> (N, H * W, C)
            (x.size(2), x.size(3))
        )
        x = self.act(self.bn(x))
        return x
```

**Comment by xunfeng2zkj** [comment]
yolov8 assert stride using cpu at task.py:288
self = self.cuda()
m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s).cuda())])
*** RuntimeError: channels == (group * group_channels) INTERNAL ASSERT FAILED at "/home/ly_lar/freedisk/dataset/night_car/yolov8/ultralytics/ultralytics/nn/DCNv4_op/src/cuda/dcnv4_cuda.cu":60, please report a bug to PyTorch. Input channels and group times group channels wont match: (%d vs %d).102464

**Comment by duzongdong** [comment]
> 我已经构建了 DCNv4_op 项目并通过以下方式进行安装：`pip install -e .`
> 
> ![image](https://private-user-images.githubusercontent.com/129521056/298957375-0c583c51-cb98-46c5-93a1-7e8811429072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjYxOTQsIm5iZiI6MTcyMjIyNTg5NCwicGF0aCI6Ii8xMjk1MjEwNTYvMjk4OTU3Mzc1LTBjNTgzYzUxLWNiOTgtNDZjNS05M2ExLTdlODgxMTQyOTA3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwNDA0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmNhZTUzMmE3M2Y0YjU5Nzg5ZWMyOTQ4MjczZjcyNTUxYzQyZTMxZDEzNGZkZmMwYjE5MmU2ZDM1MDM2YmMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f8optQYKGLImuMVZniX5eP8CG21GR5Dv-Si_F2yU-_g)
> 
> 但是当我尝试在我的项目中调用它时，我遇到了这样的错误：
> 
> ```
> (mmd) zrway@zrpgs:/data/yolov8_proj$ python /data/yolov8_proj/project/test_model.py
> 
>                    from  n    params  module                                       arguments                     
>   0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]                 
>   1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]                
>   2                  -1  2    130513  ultralytics.nn.modules.customed.PRC2f.PRC2f  [96, 96, 2, True]             
>   3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]               
>   4                  -1  4    888481  ultralytics.nn.modules.customed.PRC2f.PRC2f  [192, 192, 4, True]           
>   5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]              
>   6                  -1  4   3546433  ultralytics.nn.modules.customed.PRC2f.PRC2f  [384, 384, 4, True]           
>   7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]              
>   8                  -1  2   3512225  ultralytics.nn.modules.customed.PRC2f_DCN_v4.PRC2f_DCN_v4[576, 576, 2, True]           
>   9                  -1  1   1670992  ultralytics.nn.modules.customed.SPPF_DCN.SPPF_DCN_v4[576, 576, 5]                 
>  10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
>  11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
>  12                  -1  2   2660929  ultralytics.nn.modules.customed.PRC2f.PRC2f  [960, 384, 2]                 
>  13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
>  14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
>  15                  -1  2    703777  ultralytics.nn.modules.customed.PRC2f.PRC2f  [576, 192, 2]                 
>  16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]              
>  17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
>  18                  -1  2   2366017  ultralytics.nn.modules.customed.PRC2f.PRC2f  [576, 384, 2]                 
>  19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]              
>  20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
>  21                  -1  2   5429089  ultralytics.nn.modules.customed.PRC2f.PRC2f  [960, 576, 2]                 
>  22        [15, 18, 21]  1   3822016  ultralytics.nn.modules.head.Detect           [80, [192, 384, 576]]         
> Traceback (most recent call last):
>   File "/data/yolov8_proj/project/test_model.py", line 26, in <module>
>     model = YOLO('yolov8m.yaml').load('/data/yolov8_proj/project/yolov8m.pt')
>   File "/data/yolov8_proj/ultralytics/ultralytics/engine/model.py", line 92, in __init__
>     self._new(model, task)
>   File "/data/yolov8_proj/ultralytics/ultralytics/engine/model.py", line 142, in _new
>     self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
>   File "/data/yolov8_proj/ultralytics/ultralytics/nn/tasks.py", line 292, in __init__
>     m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))])  # forward
>   File "/data/yolov8_proj/ultralytics/ultralytics/nn/tasks.py", line 291, in <lambda>
>     forward = lambda x: self.forward(x)[0] if isinstance(m, (Segment, Pose, OBB)) else self.forward(x)
>   File "/data/yolov8_proj/ultralytics/ultralytics/nn/tasks.py", line 84, in forward
>     return self.predict(x, *args, **kwargs)
>   File "/data/yolov8_proj/ultralytics/ultralytics/nn/tasks.py", line 102, in predict
>     return self._predict_once(x, profile, visualize, embed)
>   File "/data/yolov8_proj/ultralytics/ultralytics/nn/tasks.py", line 123, in _predict_once
>     x = m(x)  # run
>   File "/home/zrway/anaconda3/envs/mmd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/data/yolov8_proj/ultralytics/ultralytics/nn/modules/customed/PRC2f_DCN_v4.py", line 177, in forward
>     y.extend(m(y[-1]) for m in self.m)
>   File "/data/yolov8_proj/ultralytics/ultralytics/nn/modules/customed/PRC2f_DCN_v4.py", line 177, in <genexpr>
>     y.extend(m(y[-1]) for m in self.m)
>   File "/home/zrway/anaconda3/envs/mmd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/data/yolov8_proj/ultralytics/ultralytics/nn/modules/customed/PRC2f_DCN_v4.py", line 49, in forward
>     return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))
>   File "/home/zrway/anaconda3/envs/mmd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/data/yolov8_proj/ultralytics/ultralytics/nn/modules/customed/PRC2f_DCN_v4.py", line 27, in forward
>     x = self.dcnv4(
>   File "/home/zrway/anaconda3/envs/mmd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/data/yolov8_proj/deps/DCNv4/DCNv4_op/DCNv4/modules/dcnv4.py", line 130, in forward
>     x = DCNv4Function.apply(
>   File "/home/zrway/anaconda3/envs/mmd/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 86, in decorate_fwd
>     return fwd(*args, **kwargs)
>   File "/data/yolov8_proj/deps/DCNv4/DCNv4_op/DCNv4/functions/dcnv4_func.py", line 103, in forward
>     output = ext.dcnv4_forward(*args)
> RuntimeError: Not implemented on the CPU
> ```
> 
> 如果您能提供一些帮助来解决这个问题，我将不胜感激。

Hi, can you give your CUDA version and pytorch and python versions, I keep getting errors compiling, thanks!
