### ISSUE TITLE
DCNv4 function and module

### ISSUE THREAD

**Issue by itruonghai** [OpenGVLab/DCNv4#3]
Dear Author,

In the [module file](https://github.com/OpenGVLab/DCNv4/blob/7d59305b5f10e1a67729cefde580ccdbd2811b6a/DCNv4_op/DCNv4/modules/flash_deform_attn.py#L132), DCNv4 function is called with 6 parameters. However, in the [forward function](https://github.com/OpenGVLab/DCNv4/blob/7d59305b5f10e1a67729cefde580ccdbd2811b6a/DCNv4_op/DCNv4/functions/flash_deform_attn_func.py#L72), it applied to 8 parameters. Could you correct it?

**Comment by YuwenXiong** [comment]
Hi, thanks for raising this up. Now this issue has been fixed with the `1.0.0.post2` release

**Comment by itruonghai** [comment]
Could you please check and rerun it again? I still find an error. It seems like the attention weight parameter does not necessary in this case. However, when I removed attention_weights parameter in the forward, it raise an error ```assert (input_spatial_shapes[:, 0] * input_spatial_shapes[:, 1]).sum() == Len_in
RuntimeError: CUDA error: an illegal memory access was encountered```

**Comment by chenzyhust** [comment]
+1

**Comment by 3bobo** [comment]
same problem
