### ISSUE TITLE
Difference between dino flashinternimage-b and dino flashinternimage-l

### ISSUE THREAD

**Issue by aliencaocao** [OpenGVLab/DCNv4#48]
Referring to the README and https://huggingface.co/OpenGVLab/DCNv4/tree/main, the weights for [dino_4scale_flash_internimage_b_1x_coco.pth](https://huggingface.co/OpenGVLab/DCNv4/blob/main/dino_4scale_flash_internimage_b_1x_coco.pth) is somehow 1.39GB while the supposely larger backbone [dino_4scale_flash_internimage_l_1x_coco.pth](https://huggingface.co/OpenGVLab/DCNv4/blob/main/dino_4scale_flash_internimage_l_1x_coco.pth) is only 964MB. Is this to be expected?

Given that the flash intern image Large backbone is already 1.25GB [flash_intern_image_l_22k_384.pth](https://huggingface.co/OpenGVLab/DCNv4/blob/main/flash_intern_image_l_22k_384.pth), I am suspecting that the checkpoint was saved wrongly

**Comment by zhiqi-li** [comment]
We apologize for the misunderstanding. We removed the optimizer parameter in dino_4scale_flash_internimage_l_1x_coco.pth to halve the model size, which makes it easier for us to upload the model.

**Comment by aliencaocao** [comment]
Thanks for clarifying.
