### ISSUE TITLE
RuntimeError: "dcnv4_backward_cuda" not implemented for 'BFloat16'

### ISSUE THREAD

**Issue by DsaltYfish** [OpenGVLab/DCNv4#8]
I have been using PyTorch's native Automatic Mixed Precision (AMP) feature and specified the data type as bf16 (bfloat16). However, I encountered an error during the backward propagation step. I would like to know if this is due to a lack of framework support or if I made an error in my usage.

**Comment by YuwenXiong** [comment]
Hi, thanks for raising this up. Now this issue has been fixed with the `1.0.0.post1` release

**Comment by DsaltYfish** [comment]
After upgrading to version 1.0.0.post2, I encountered an issue. When performing backpropagation, I received an error message saying "expected scalar type Float but found BFloat16".

**Comment by jiarenyf** [comment]
Meeting the same problem ...

**Comment by JiaHeng-DLUT** [comment]
+1. same problem.
